version: '3'
services:
  mongo:
    image: 'mongo:4.4.6'
    container_name: 'ecrl-db-mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/db:/data/db
  mongo_seed:
    image: 'mongo:4.4.6'
    container_name: 'ecrl-db-mongo-seed'
    links:
      - mongo
    volumes:
      - ./mongo:/mongo
    command: /mongo/import.sh
  web:
    depends_on:
      - 'mongo'
    container_name: 'ecrl-db-web'
    build: .
    environment:
      - MONGODB_CONNSTRING=mongodb://mongo:27017
    ports:
      - '8080:8080'